export interface User {
    id: number;
    name: string;
    email: string;
    role: string;
    job_title: string;
    
  }

export const usrs: User[] = [{"id":1,"name":"Chastity Dwelling","email":"cdwelling0@icio.us","job_title":"Sales Associate","role":"Supervisor"},
{"id":2,"name":"Ab Loyndon","email":"aloyndon1@nyu.edu","job_title":"Quality Control Specialist","role":"Supervisor"},
{"id":3,"name":"Annissa Michael","email":"amichael2@privacy.gov.au","job_title":"Health Coach I","role":"Construction Foreman"},
{"id":4,"name":"Isabel Syseland","email":"isyseland3@tamu.edu","job_title":"Associate Professor","role":"Surveyor"},
{"id":5,"name":"Karina Scotfurth","email":"kscotfurth4@tuttocitta.it","job_title":"GIS Technical Architect","role":"Construction Foreman"},
{"id":6,"name":"Gussi Callingham","email":"gcallingham5@ft.com","job_title":"Information Systems Manager","role":"Supervisor"},
{"id":7,"name":"Dasi Dallemore","email":"ddallemore6@g.co","job_title":"Software Consultant","role":"Project Manager"},
{"id":8,"name":"Sebastian Hagstone","email":"shagstone7@wikimedia.org","job_title":"Accounting Assistant II","role":"Electrician"},
{"id":9,"name":"Sharyl Birtwell","email":"sbirtwell8@scribd.com","job_title":"Electrical Engineer","role":"Construction Foreman"},
{"id":10,"name":"Waneta Scotchforth","email":"wscotchforth9@webmd.com","job_title":"Programmer Analyst III","role":"Surveyor"},
{"id":11,"name":"Odette Ratray","email":"oratraya@nydailynews.com","job_title":"Speech Pathologist","role":"Construction Expeditor"},
{"id":12,"name":"Florian Garlant","email":"fgarlantb@woothemes.com","job_title":"Operator","role":"Construction Worker"},
{"id":13,"name":"Francoise Drioli","email":"fdriolic@vimeo.com","job_title":"Programmer Analyst II","role":"Construction Expeditor"},
{"id":14,"name":"Nonie Sparry","email":"nsparryd@time.com","job_title":"Chief Design Engineer","role":"Construction Worker"},
{"id":15,"name":"Marlena Haworth","email":"mhaworthe@theguardian.com","job_title":"Geological Engineer","role":"Engineer"},
{"id":16,"name":"Fannie Ternault","email":"fternaultf@sciencedaily.com","job_title":"Software Engineer I","role":"Electrician"},
{"id":17,"name":"Lock Bottjer","email":"lbottjerg@indiatimes.com","job_title":"Geological Engineer","role":"Supervisor"},
{"id":18,"name":"Ulberto Walrond","email":"uwalrondh@aboutads.info","job_title":"Administrative Assistant III","role":"Surveyor"},
{"id":19,"name":"Ruy Rider","email":"rrideri@umich.edu","job_title":"Geological Engineer","role":"Construction Worker"},
{"id":20,"name":"Frederich Shiril","email":"fshirilj@cisco.com","job_title":"Sales Associate","role":"Architect"},
{"id":21,"name":"Berty Chancelier","email":"bchancelierk@pen.io","job_title":"Occupational Therapist","role":"Surveyor"},
{"id":22,"name":"Fredric Craggs","email":"fcraggsl@hexun.com","job_title":"Tax Accountant","role":"Construction Foreman"},
{"id":23,"name":"Granny Croux","email":"gcrouxm@bbb.org","job_title":"Cost Accountant","role":"Construction Foreman"},
{"id":24,"name":"Shay Melsome","email":"smelsomen@multiply.com","job_title":"Information Systems Manager","role":"Construction Manager"},
{"id":25,"name":"Brigg Simmens","email":"bsimmenso@is.gd","job_title":"Human Resources Manager","role":"Project Manager"},
{"id":26,"name":"Norbert Foxon","email":"nfoxonp@nymag.com","job_title":"Food Chemist","role":"Supervisor"},
{"id":27,"name":"Lily Gilburt","email":"lgilburtq@sun.com","job_title":"Sales Representative","role":"Electrician"},
{"id":28,"name":"Kristy Antonias","email":"kantoniasr@google.de","job_title":"Nurse Practicioner","role":"Supervisor"},
{"id":29,"name":"Derick Wrinch","email":"dwrinchs@cisco.com","job_title":"Administrative Officer","role":"Estimator"},
{"id":30,"name":"Karrah Jedrysik","email":"kjedrysikt@is.gd","job_title":"Cost Accountant","role":"Subcontractor"},
{"id":31,"name":"Granger Holde","email":"gholdeu@wordpress.com","job_title":"Sales Representative","role":"Construction Worker"},
{"id":32,"name":"Duffie Jiruch","email":"djiruchv@rakuten.co.jp","job_title":"Analyst Programmer","role":"Construction Expeditor"},
{"id":33,"name":"Eleen MacKay","email":"emackayw@surveymonkey.com","job_title":"Financial Advisor","role":"Engineer"},
{"id":34,"name":"Garvin Nosworthy","email":"gnosworthyx@google.com","job_title":"Social Worker","role":"Supervisor"},
{"id":35,"name":"Denna Seller","email":"dsellery@europa.eu","job_title":"Developer II","role":"Construction Expeditor"},
{"id":36,"name":"Andrej Dechelette","email":"adechelettez@nbcnews.com","job_title":"Data Coordinator","role":"Architect"},
{"id":37,"name":"Torin Stanley","email":"tstanley10@mayoclinic.com","job_title":"Safety Technician I","role":"Supervisor"},
{"id":38,"name":"Olva Mosedall","email":"omosedall11@utexas.edu","job_title":"Marketing Manager","role":"Construction Manager"},
{"id":39,"name":"Moore Garioch","email":"mgarioch12@fc2.com","job_title":"Statistician III","role":"Supervisor"},
{"id":40,"name":"Ailyn Norvill","email":"anorvill13@nationalgeographic.com","job_title":"Teacher","role":"Engineer"},
{"id":41,"name":"Jobie Rigbye","email":"jrigbye14@go.com","job_title":"Assistant Media Planner","role":"Supervisor"},
{"id":42,"name":"Nevin Whitehouse","email":"nwhitehouse15@acquirethisname.com","job_title":"Geological Engineer","role":"Subcontractor"},
{"id":43,"name":"Channa Lauga","email":"clauga16@dot.gov","job_title":"Teacher","role":"Surveyor"},
{"id":44,"name":"Lucias Waiting","email":"lwaiting17@github.com","job_title":"Tax Accountant","role":"Architect"},
{"id":45,"name":"Bruce Blackster","email":"bblackster18@etsy.com","job_title":"Senior Editor","role":"Electrician"},
{"id":46,"name":"Angelo Mulligan","email":"amulligan19@latimes.com","job_title":"Financial Analyst","role":"Project Manager"},
{"id":47,"name":"Baxie Toffolini","email":"btoffolini1a@answers.com","job_title":"Research Assistant IV","role":"Engineer"},
{"id":48,"name":"Colman Pawlik","email":"cpawlik1b@jugem.jp","job_title":"Data Coordinator","role":"Construction Worker"},
{"id":49,"name":"Florentia Wardley","email":"fwardley1c@ameblo.jp","job_title":"Senior Developer","role":"Supervisor"},
{"id":50,"name":"Dyna Sigart","email":"dsigart1d@webnode.com","job_title":"Programmer Analyst III","role":"Subcontractor"},
{"id":51,"name":"Foster Tame","email":"ftame1e@nature.com","job_title":"Database Administrator IV","role":"Architect"},
{"id":52,"name":"Dina Klawi","email":"dklawi1f@cargocollective.com","job_title":"Design Engineer","role":"Surveyor"},
{"id":53,"name":"Jillene Lorryman","email":"jlorryman1g@microsoft.com","job_title":"Software Engineer I","role":"Construction Manager"},
{"id":54,"name":"Karney Frammingham","email":"kframmingham1h@earthlink.net","job_title":"Programmer II","role":"Construction Expeditor"},
{"id":55,"name":"Harp Eydel","email":"heydel1i@earthlink.net","job_title":"Recruiter","role":"Subcontractor"},
{"id":56,"name":"Janessa Edward","email":"jedward1j@vimeo.com","job_title":"Staff Scientist","role":"Engineer"},
{"id":57,"name":"Kendricks Falkus","email":"kfalkus1k@prlog.org","job_title":"Programmer Analyst IV","role":"Construction Manager"},
{"id":58,"name":"Alasdair Crosbie","email":"acrosbie1l@wiley.com","job_title":"VP Product Management","role":"Construction Manager"},
{"id":59,"name":"Gert Gregoretti","email":"ggregoretti1m@tmall.com","job_title":"Analog Circuit Design manager","role":"Electrician"},
{"id":60,"name":"Izaak Heis","email":"iheis1n@gmpg.org","job_title":"Cost Accountant","role":"Project Manager"},
{"id":61,"name":"Aurelea Southam","email":"asoutham1o@ow.ly","job_title":"GIS Technical Architect","role":"Construction Worker"},
{"id":62,"name":"Nataline Mildenhall","email":"nmildenhall1p@marriott.com","job_title":"Human Resources Assistant I","role":"Construction Expeditor"},
{"id":63,"name":"Sidonnie Yerill","email":"syerill1q@amazon.com","job_title":"Media Manager I","role":"Surveyor"},
{"id":64,"name":"Jilli Manhare","email":"jmanhare1r@1und1.de","job_title":"Software Consultant","role":"Subcontractor"},
{"id":65,"name":"Randal Olney","email":"rolney1s@zimbio.com","job_title":"Recruiting Manager","role":"Estimator"},
{"id":66,"name":"Junia Silbert","email":"jsilbert1t@oakley.com","job_title":"Internal Auditor","role":"Engineer"},
{"id":67,"name":"Clyde Rentilll","email":"crentilll1u@google.nl","job_title":"Statistician IV","role":"Supervisor"},
{"id":68,"name":"Idalina Heeps","email":"iheeps1v@mapy.cz","job_title":"Structural Analysis Engineer","role":"Engineer"},
{"id":69,"name":"Cecil Orrick","email":"corrick1w@xrea.com","job_title":"Design Engineer","role":"Construction Worker"},
{"id":70,"name":"Ber Trevethan","email":"btrevethan1x@google.ca","job_title":"Payment Adjustment Coordinator","role":"Construction Worker"},
{"id":71,"name":"Ailbert Belsham","email":"abelsham1y@bandcamp.com","job_title":"Sales Representative","role":"Construction Manager"},
{"id":72,"name":"Riordan Vayro","email":"rvayro1z@eepurl.com","job_title":"Operator","role":"Estimator"},
{"id":73,"name":"Lotty Menure","email":"lmenure20@com.com","job_title":"Account Representative I","role":"Construction Foreman"},
{"id":74,"name":"Hannah Wyllis","email":"hwyllis21@about.me","job_title":"Nuclear Power Engineer","role":"Supervisor"},
{"id":75,"name":"Dot Simkiss","email":"dsimkiss22@sphinn.com","job_title":"VP Quality Control","role":"Project Manager"},
{"id":76,"name":"Addie Ghiraldi","email":"aghiraldi23@imageshack.us","job_title":"Software Test Engineer II","role":"Construction Manager"},
{"id":77,"name":"Herminia Onthank","email":"honthank24@flickr.com","job_title":"Nuclear Power Engineer","role":"Estimator"},
{"id":78,"name":"Bayard Clatworthy","email":"bclatworthy25@businessweek.com","job_title":"Nuclear Power Engineer","role":"Architect"},
{"id":79,"name":"Arabele Adamides","email":"aadamides26@typepad.com","job_title":"Administrative Assistant I","role":"Electrician"},
{"id":80,"name":"Madelene Roslen","email":"mroslen27@mozilla.com","job_title":"Speech Pathologist","role":"Surveyor"},
{"id":81,"name":"Federica O'Griffin","email":"fogriffin28@lycos.com","job_title":"Structural Analysis Engineer","role":"Subcontractor"},
{"id":82,"name":"Alexandros Pomfrey","email":"apomfrey29@squidoo.com","job_title":"Chief Design Engineer","role":"Estimator"},
{"id":83,"name":"Walsh Walas","email":"wwalas2a@google.cn","job_title":"Product Engineer","role":"Electrician"},
{"id":84,"name":"Aldwin Lummus","email":"alummus2b@unesco.org","job_title":"Legal Assistant","role":"Electrician"},
{"id":85,"name":"Maryann Briton","email":"mbriton2c@wired.com","job_title":"Mechanical Systems Engineer","role":"Construction Expeditor"},
{"id":86,"name":"Chevalier Medgewick","email":"cmedgewick2d@multiply.com","job_title":"Clinical Specialist","role":"Construction Foreman"},
{"id":87,"name":"Demetris Frampton","email":"dframpton2e@mayoclinic.com","job_title":"Paralegal","role":"Engineer"},
{"id":88,"name":"Laney Whyatt","email":"lwhyatt2f@artisteer.com","job_title":"Software Consultant","role":"Supervisor"},
{"id":89,"name":"Sandro Seedhouse","email":"sseedhouse2g@salon.com","job_title":"Senior Cost Accountant","role":"Construction Worker"},
{"id":90,"name":"Andeee Wix","email":"awix2h@mac.com","job_title":"Office Assistant IV","role":"Construction Foreman"},
{"id":91,"name":"Richmond Niccols","email":"rniccols2i@mapquest.com","job_title":"Staff Accountant II","role":"Construction Foreman"},
{"id":92,"name":"Tamara Bussen","email":"tbussen2j@ezinearticles.com","job_title":"Operator","role":"Estimator"},
{"id":93,"name":"Ingram Summerscales","email":"isummerscales2k@admin.ch","job_title":"Operator","role":"Subcontractor"},
{"id":94,"name":"Elga Alam","email":"ealam2l@theatlantic.com","job_title":"Geological Engineer","role":"Construction Foreman"},
{"id":95,"name":"Jamey Ashcroft","email":"jashcroft2m@unesco.org","job_title":"Business Systems Development Analyst","role":"Construction Expeditor"},
{"id":96,"name":"Magda Haslin","email":"mhaslin2n@myspace.com","job_title":"Database Administrator III","role":"Surveyor"},
{"id":97,"name":"Stoddard Lyngsted","email":"slyngsted2o@deliciousdays.com","job_title":"Research Nurse","role":"Architect"},
{"id":98,"name":"Melamie Wey","email":"mwey2p@msu.edu","job_title":"Community Outreach Specialist","role":"Subcontractor"},
{"id":99,"name":"Karin Nickerson","email":"knickerson2q@hc360.com","job_title":"Research Associate","role":"Electrician"},
{"id":100,"name":"Ingrid Leavy","email":"ileavy2r@purevolume.com","job_title":"Automation Specialist II","role":"Electrician"}]

